load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Core",
    module_name = "Core",
    srcs = ["Rest.swift",],
    visibility = ["//visibility:public"],
)